### ISSUE TITLE
Add in auto# of .csv files

### ISSUE THREAD

**Issue by aguita** [beccasafan/pgm-multiloc#4]
IT'd be great to add in the ability to include multiple CSV files within the script.   <users1.csv> <users2.csv>.   I find it easier to include the csvs in my scripts than many multiple users, so I can maintain the users separately (add, replace, delete).

**Comment by aguita** [comment]
Within the script, you mention {index}.   Could use that such as:    users{index}.csv

**Comment by beccasafan** [comment]
Yup, you can go ahead and do this now!

In the worker template, you could add `-ac users{index}.csv` and Worker1 would have `-ac users1.csv`. The templates make the commands completely customizable.

**Comment by aguita** [comment]
Ahh, got it.  Already there.  Perfect.
