### ISSUE TITLE
Script creation for Windows .bat file has all the -ns commands as runserver.exe

### ISSUE THREAD

**Issue by aguita** [beccasafan/pgm-multiloc#8]
Bug:  
.bat file created creates all the subsequent lines as 

... /MIN python.exe runserver.exe  ...
instead of 
.. /MIN python.exe runserver.py  ...

The -os line does it correctly.

**Comment by beccasafan** [comment]
Fixed by b8f026c971e8afdb76e6f21f89a8a346b14b9fe0
